feat(metrics): add size metric to MongoDB
iotaledger/inx-chronicle pull request #183
Opened 2022-05-20 20:18 UTC by pvdrz

2022-05-21 10:54 UTC, Alexandcoats reviewed
I would probably separate the various tasks into actors, and refactor the `Retry` stuff into an event struct which would get delayed. Or, alternatively, the actors can simply fail and be restarted by the supervisor.

2022-05-23 15:19 UTC, grtlr approved these changes

2022-05-23 15:20 UTC, grtlr requested changes

2022-05-23 15:20 UTC, grtlr commented on bin/inx-chronicle/src/main.rs
> +        cx.spawn_child(metrics::MetricsWorker::new(db, config.metrics.clone()))
Sorry, accidentally approved :(

2022-05-27 12:58 UTC, grtlr approved these changes

2022-05-27 12:58 UTC, merged