feat(cli): split `influxdb` feature properly
iotaledger/inx-chronicle pull request #870
Opened 2022-11-08 17:29 UTC by Alexandcoats

## Linked Issues

* Closes #865

## Notes to Reviewer

As a reviewer, please pay particular attention to the following areas when reviewing this PR and tick the above boxes after you have completed the steps.

#### Config Changes
* [ ] Ensure proper order in which CLI and config arguments are applied.
* [ ] Ensure that config changes work with individual build features.

#### INX Changes
* [ ] Run chronicle using an INX connection.
* [ ] Use new `metrics_enabled` and `analytics_enabled` CLI/config flags

2022-11-09 08:13 UTC, grtlr commented on src/db/mod.rs
>  /// Module containing InfluxDb types and traits.
```suggestion
/// Module containing InfluxDb types and traits.
#[cfg(any(feature = "analytics", feature = "metrics"))]
```

2022-11-09 08:17 UTC, grtlr requested changes
Currently fails to compile with `cargo ci-check-features`.

2022-11-11 09:20 UTC, grtlr requested changes
The CLI flags don't work, because we never check for `metrics_enabled` in `stardust_inx`. We should probably add `metrics_enabled` and `analytics_enabled` fields to our `InfluxDb` type.

2022-11-14 14:17 UTC, Alexandcoats commented on src/bin/inx-chronicle/stardust_inx/mod.rs
> +            .then(std::time::Instant::now);
Yeah, probably not a huge difference either way.

2022-11-16 16:57 UTC, grtlr approved these changes

2022-11-16 17:11 UTC, Alex6323 approved these changes

2022-11-16 17:54 UTC, merged