Refactor/config/config refactor
iotaledger/inx-chronicle pull request #979
Opened 2022-12-13 20:47 UTC by Alex6323

## Linked Issues

* Closes #966
* Closes #947
* Closes #788 

## Notes to Reviewer

As a reviewer, please pay particular attention to the following areas when reviewing this PR and tick the above boxes after you have completed the steps.

#### Config Changes
* [ ] Ensure proper order in which CLI and config arguments are applied.
* [ ] Ensure that config changes work with individual build features by running `cargo ci-check-features`.

2022-12-19 12:37 UTC, Alex6323 commented on .github/workflows/_test_int.yml
> +          #mongodb-replica-set: test-rs
basically because of this issue:

2022-12-20 09:44 UTC, grtlr commented on src/bin/inx-chronicle/cli.rs
> +        // Note: all unwraps are fine because we defined defaults for all, so none of them can be None ;)
Which `unwraps`?

2022-12-20 10:02 UTC, Alex6323 commented on src/bin/inx-chronicle/cli.rs
> +        // Note: all unwraps are fine because we defined defaults for all, so none of them can be None ;)
haha, forgot to remove this note

2022-12-20 12:17 UTC, Alex6323 commented on src/bin/inx-chronicle/cli.rs
> +    pub fn get_config(&self) -> ChronicleConfig {
good catch

2022-12-21 14:15 UTC, grtlr requested changes
Please make sure `cargo ci-check-features` command passes.

2022-12-22 13:03 UTC, grtlr requested changes

2022-12-22 13:03 UTC, grtlr commented on src/bin/inx-chronicle/cli.rs
> +            metrics_database_name: String::new(),
Shouldn't those be feature-gated in `InfluxDbConfig` too so that this step would not be necessary?

2022-12-23 07:00 UTC, grtlr commented
Could you please also do https://github.com/iotaledger/inx-chronicle/issues/1000 as part of this PR? 🙏

2022-12-23 10:58 UTC, Alex6323 commented on src/db/mongodb/collection.rs
> +    pub _ignored: usize,
Can we solve this when we deal with the visibility modifiers. This has nothing to do with this PR really. It's just to make the CI happy, and I think we should address this separatedly.

2022-12-23 13:33 UTC, grtlr commented on README.md
> +Docker compose will automatically load credentials for different services from a `.env` file that must be located in the same directory as the `docker-compose.yml` file. You therefore must create suc
```suggestion
Docker compose will automatically load credentials for different services from a `.env` file that must either be located in the same directory as the `docker-compose.yml` file, or specified using the `--env-file` flag. You therefore must create such a file before you do a `docker compose up`. An example `.env` file could look like this:
```

2022-12-23 16:45 UTC, grtlr approved these changes

2022-12-23 16:45 UTC, merged